services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9095:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  snyk-exporter:
    build:
      context: ./snyk
      dockerfile: Dockerfile
    container_name: snyk-exporter-metrics
    ports:
      - "9469:9469"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prom_data: