{
 "title": "Snyk_Security_Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Distribution des vulnérabilités par sévérité",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_issues_by_severity_total) by (severity)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution des vulnérabilités par service et sévérité",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(severity, service) (snyk_issues_by_severity_total)",
     "legendFormat": "{{severity}} - {{service}}"
    }
   ]
  },
  {
   "title": "Vulnérabilités critiques par service",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_issues_by_severity_total{severity=\"critical\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total des vulnérabilités par services",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snyk_issues_total{job=\"snyk_metrics\"}",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}