global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'snyk_metrics'
    static_configs:
      - targets: ['snyk-exporter-metrics:9469']
    metrics_path: '/metrics'