prometheus:
  image: prom/prometheus
  tag: latest
  service:
    type: ClusterIP
    port: 9090
  resources: {}

grafana:
  image: grafana/grafana
  tag: latest
  service:
    type: ClusterIP
    port: 3000
  adminUser: admin
  adminPassword: grafana
  resources: {}

snykExporter:
  image: snyl-exporter
  tag: latest
  service:
    type: ClusterIP
    port: 9469
  resources: {}